eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
ribbon:
  ReadTimeout: 60000
server:
  port: 0
spring:
  application:
    name: FlightBook
  datasource:
    password: pass@word1
    url: jdbc:mysql://localhost:3306/Sample
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
